// Generate public/robots.txt and public/sitemap.xml for the current domain.
//
// Files under public/ are copied to the build verbatim — Vite does not
// substitute variables inside them the way it does in index.html. So they are
// written here instead, and `npm run build` runs this first (see the "prebuild"
// script in package.json).
//
// The domain comes from scripts/site-url.mjs, the same resolver vite.config.js
// uses for index.html, so the two can never disagree.
//
// Usage: node scripts/build-seo.mjs
import { writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { resolveSiteUrl, SITE_URL_HELP } from './site-url.mjs'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

const url = resolveSiteUrl()
if (!url) {
  // Only reachable when there is no .env AND we are not on Vercel — i.e. a
  // local build on a fresh clone. Stopping beats shipping a canonical tag that
  // points at the wrong host, which is silent and hard to notice.
  console.error('\n  build-seo: cannot determine the site URL — build stopped.\n\n' + SITE_URL_HELP)
  process.exit(1)
}

const robots = `# Generated by scripts/build-seo.mjs — edit that file, not this one.
User-agent: *
Allow: /

# Admin area — nothing there for a crawler, and it should never be indexed.
Disallow: /admin

Sitemap: ${url}/sitemap.xml
`

// /resultats and /reserver are left out on purpose: they are search-result and
// transactional pages that only make sense with query parameters.
const pages = [
  { loc: '/',       changefreq: 'weekly', priority: '1.0' },
  { loc: '/flotte', changefreq: 'weekly', priority: '0.8' },
]

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/build-seo.mjs — edit that file, not this one. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${pages.map(p => `  <url>
    <loc>${url}${p.loc}</loc>
    <changefreq>${p.changefreq}</changefreq>
    <priority>${p.priority}</priority>
  </url>`).join('\n')}
</urlset>
`

await writeFile(join(root, 'public', 'robots.txt'), robots, 'utf8')
await writeFile(join(root, 'public', 'sitemap.xml'), sitemap, 'utf8')
console.log(`build-seo: robots.txt + sitemap.xml written for ${url}`)
