// Generate public/robots.txt and public/sitemap.xml from VITE_SITE_URL.
//
// Files under public/ are copied to the build verbatim — Vite does not
// substitute env vars inside them the way it does in index.html. So they are
// written here instead, and `npm run build` runs this first (see the "prebuild"
// script in package.json). Set the domain ONCE in .env; nothing else hardcodes
// it.
//
// Usage: node scripts/build-seo.mjs
import { writeFile, readFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

// Minimal .env reader — this runs before Vite, so import.meta.env isn't
// available and we don't want a dotenv dependency for four lines of parsing.
async function siteUrl() {
  if (process.env.VITE_SITE_URL) return process.env.VITE_SITE_URL.replace(/\/+$/, '')
  try {
    const env = await readFile(join(root, '.env'), 'utf8')
    const line = env.split(/\r?\n/).find(l => l.trim().startsWith('VITE_SITE_URL='))
    if (line) {
      const v = line.slice(line.indexOf('=') + 1).trim().replace(/^["']|["']$/g, '')
      if (v) return v.replace(/\/+$/, '')
    }
  } catch { /* no .env — fall through */ }
  return null
}

const url = await siteUrl()
if (!url) {
  // Fail the build rather than ship a canonical tag pointing at the wrong host
  // or a literal "%VITE_SITE_URL%" — both are silent and hard to notice.
  console.error(
    '\n  build-seo: VITE_SITE_URL is not set — build stopped.\n\n' +
    '  Locally : add it to .env\n' +
    '  Vercel  : Settings → Environment Variables → add VITE_SITE_URL\n\n' +
    '  Example : VITE_SITE_URL=https://votre-domaine.ma   (no trailing slash)\n'
  )
  process.exit(1)
}

const robots = `# Generated by scripts/build-seo.mjs — edit that file, not this one.
User-agent: *
Allow: /

# Admin area — nothing there for a crawler, and it should never be indexed.
Disallow: /admin

Sitemap: ${url}/sitemap.xml
`

// /resultats and /reserver are left out on purpose: they are search-result and
// transactional pages that only make sense with query parameters.
const pages = [
  { loc: '/',       changefreq: 'weekly', priority: '1.0' },
  { loc: '/flotte', changefreq: 'weekly', priority: '0.8' },
]

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/build-seo.mjs — edit that file, not this one. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${pages.map(p => `  <url>
    <loc>${url}${p.loc}</loc>
    <changefreq>${p.changefreq}</changefreq>
    <priority>${p.priority}</priority>
  </url>`).join('\n')}
</urlset>
`

await writeFile(join(root, 'public', 'robots.txt'), robots, 'utf8')
await writeFile(join(root, 'public', 'sitemap.xml'), sitemap, 'utf8')
console.log(`build-seo: robots.txt + sitemap.xml written for ${url}`)
